version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: qa_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - qa-network

volumes:
  postgres-data:

networks:
  qa-network:
